routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('appointments');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('appointments', 'AppointmentController')->middleware('auth');
Route::get('appointments/changestatus/{aid}/{sid}', 'AppointmentController@changeStatus')->name('appointments.changestatus')->middleware('auth');
Route::delete('appointments-bulk-delete', 'AppointmentController@deleteAll');
Route::get('appointments/delete/{id}', 'AppointmentController@destroy')->name('appointment.delete');

Route::resource('treatments', 'TreatmentController')->middleware('auth');
Route::delete('treatments-bulk-delete', 'TreatmentController@deleteAll');

app/Appointment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Kyslik\ColumnSortable\Sortable;

class Appointment extends Model
{
    use Sortable;

    protected $fillable = ['user_id', 'treatment_id', 'appointment_status_id', 'payment_status_id', 'start_time'];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function treatment(){
        return $this->belongsTo('App\Treatment');
    }

    public function appointmentStatus(){
        return $this->belongsTo('App\AppointmentStatus');
    }

    public function paymentStatus(){
        return $this->belongsTo('App\PaymentStatus');
    }

    public function getDateAttribute($value)
    {
        return Carbon::make($this->start_time)->toDateString();
    }

    public function getTimeAttribute($value)
    {
        return Carbon::make($this->start_time)->toTimeString();
    }
}

app/Http/Controllers/AppointmentController.php
<?php

namespace App\Http\Controllers;

use App\Appointment;
use App\AppointmentStatus;
use App\PaymentStatus;
use App\Role;
use App\Treatment;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

class AppointmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        if (auth()->user()->role->name === 'admin') {
            $appointmentsQuery = Appointment::query();
        } else {
            $appointmentsQuery = Appointment::where('user_id', auth()->id());
        }
        if ($sortBy = $request->input('sort')) {
            if ($request->input('direction')) {
                $appointmentsQuery->orderBy($sortBy, $request->input('direction'));
            } else {
                $appointmentsQuery->orderBy($sortBy);
            }
        }

        $appointments = $appointmentsQuery->paginate(10);
        return view('appointments.index', compact('appointments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function create()
    {
        $users = User::where('role_id', Role::where('name', 'customer')->first()->id)->get();
        $treatments = Treatment::all();
        return view('appointments.create', compact('users', 'treatments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        $appointment = new Appointment($request->all());
        if (auth()->user()->role->name === 'customer') {
            $appointment->user_id = auth()->id();
        }
        $appointment->start_time = Carbon::make($request->input('start_time'))->toDateTime();
        $appointment->appointment_status_id = AppointmentStatus::where('name', 'pending')->first()->id;
        $appointment->payment_status_id = PaymentStatus::where('name', 'Not paid')->first()->id;
        $appointment->save();
        return redirect('appointments');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function edit($id)
    {
        $appointment = Appointment::findOrFail($id);
        $treatments = Treatment::all();
        $payment_statuses = PaymentStatus::all();
        $appointment_statuses = AppointmentStatus::all();
        $users = User::where('role_id', Role::where('name', 'customer')->first()->id)->get();
        return view('appointments.edit', compact('appointment', 'users', 'treatments', 'appointment_statuses', 'payment_statuses'));
    }

    public function changeStatus($aid, $sid)
    {
        $appointment = Appointment::findOrFail($aid);
        if(Gate::allows('change-status', $appointment))
        {
            $from = $appointment->appointmentStatus->id;
            if(!AppointmentStatus::allowed($from,$sid)) return redirect('appointments');
            $appointment->appointment_status_id = $sid;
            $appointment->save();
        }else{
            Session::flash('notallowed', 'You are not allowed to change the status of the appointment because you are not admin');
        }
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $appointment = Appointment::findOrFail($id);
        if (auth()->user()->role->name === 'admin') {
            $appointment->user_id = $request->input('user_id');
            $appointment->appointment_status_id = $request->input('appointment_status_id');
            $appointment->payment_status_id = $request->input('payment_status_id');
        } else {
            $appointment->appointment_status_id = AppointmentStatus::where('name', 'pending')->first()->id;
        }
        $appointment->treatment_id = $request->input('treatment_id');
        $appointment->start_time = Carbon::make($request->input('start_time'))->toDateTime();


        $appointment->save();
        return redirect('appointments');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $appointment = Appointment::findOrFail($id);
        $appointment->delete();
        return redirect('appointments');
    }


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function deleteAll(Request $request)
    {
        $ids = $request->ids;
        DB::table("appointments")->whereIn('id', explode(",", $ids))->delete();
        return response()->json(['success' => "Appointments Deleted successfully."]);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        $validate['start_time'] = Carbon::make($data['start_time'])->hour;
        $validate['start_after_day'] = Carbon::make($data['start_time']) > Carbon::now()->addDay();
        $validate['round_hour'] = Carbon::make($data['start_time'])->minute;
        $validate['start_day'] = !Carbon::make($data['start_time'])->isSaturday() && !Carbon::make($data['start_time'])->isFriday();
        $validate['appointment_collisions'] = Appointment::where('start_time', '=', Carbon::make($data['start_time']))->count();

        $rules = [
            'start_time' => ['required', 'numeric', 'between:8,17'],
            'round_hour' => ['required', 'in:0'],
            'start_day' => ['required', 'accepted'],
            'appointment_collisions' => ['required', 'in:0'],
        ];

        $messages = [
            'start_time.between' => "The start time should be between 8AM and 17PM",
            'round_hour.in' => "The appointment time must be a round hour",
            'start_day.accepted' => "The start day should be between Sunday and Thursday",
            'appointment_collisions.in' => "The appointment time is not free",
        ];

        if (auth()->user()->role->name === 'user') {
            $rules['start_after_day'] = ['required', 'accepted'];
            $messages['start_after_day.accepted'] = 'The start time should be in more then 24 hours';
        }

        return Validator::make($validate, $rules, $messages);
    }
}

resources/views/appointments/create.blade.php
@extends('layouts.moran')

@section('title', 'Create Appointment')

@section('content')
    <h1>Create Appointment</h1>
    <form method="post" action="{{action('AppointmentController@store')}}">
        @csrf
        @if(auth()->user()->role->name === 'admin')
            <div class="form-group">
                <label for="user_id">Customer</label>
                <select class="form-control" name="user_id">
                    @foreach($users as $user)
                        <option value="{{$user->id}}">{{$user->name}}</option>
                    @endforeach
                </select>
            </div>
        @endif
        <div>
            <label for="treatment_id">Treatment</label>
            <select class="form-control" name="treatment_id">
                @foreach($treatments as $treatment)
                    <option value="{{$treatment->id}}">{{$treatment->name}}, Price: {{$treatment->cost}}, Duration: {{$treatment->duration}} Minutes</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="start_time">Date and Time</label>
            <div>Please book appointment between Sunday-Thursday, 8AM-17PM, Only round hours, and start in more then 24 hours</div>
            <input type="datetime-local" class="form-control" name="start_time">
            @error('start_time')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
            @error('round_hour')
            <br>
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
            @error('start_day')
            <br>
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
            @error('appointment_collisions')
            <br>
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
            @error('start_after_day')
            <br>
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
        <div>
            <input type="submit" name="submit" value="Create appointment">
        </div>
    </form>

@endsection

resources/views/appointments/edit.blade.php
@extends('layouts.moran')

@section('title', 'Edit Appointment')

@section('content')
    <h1>Edit Appointment</h1>
    <form method="post" action="{{action('AppointmentController@update', $appointment->id)}}">
        @csrf
        @METHOD('PATCH')
        @if(auth()->user()->role->name === 'admin')
            <div class="form-group">
                <label for="user_id">Customer</label>
                <select class="form-control" name="user_id">
                    @foreach($users as $user)
                        <option value="{{$user->id}}" {{$user->id === $appointment->user_id ? 'selected' : ''}}>{{$user->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="appointment_status_id">Appointment status</label>
                    @if (null != App\AppointmentStatus::next($appointment->appointment_status_id))
                        <div class="select-wrapper">
                            <select name="appointment_status_id" id="appointment_status_id">
                                @foreach(App\AppointmentStatus::next($appointment->appointment_status_id) as $appointment_status)
                                    <option value="{{$appointment_status->id}}" {{$appointment_status->id === $appointment->appointment_status_id ? 'selected' : ''}}>{{$appointment_status->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    @else
                        <input value="{{$appointment->appointmentStatus->id}}"  hidden type="number" class="form-control" name="appointment_status_id">
                        <input value="{{$appointment->appointmentStatus->name}}" disabled>
                    @endif
            </div>
            <div class="form-group">
                <label for="payment_status_id">Payment Status</label>
                <select class="form-control" name="payment_status_id">
                    @foreach($payment_statuses as $payment_status)
                        <option value="{{$payment_status->id}}" {{$payment_status->id === $appointment->payment_status_id ? 'selected' : ''}}>{{$payment_status->name}}</option>
                    @endforeach
                </select>
            </div>
        @endif
        <div>
            <label for="treatment_id">Treatment</label>
            <select class="form-control" name="treatment_id">
                @foreach($treatments as $treatment)
                    <option value="{{$treatment->id}}" {{$treatment->id === $appointment->treatment_id ? 'selected' : ''}}>{{$treatment->name}}
                        , Price: {{$treatment->cost}}, Duration: {{$treatment->duration}} Minutes
                    </option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="start_time">Date and Time</label>
            <input value="{{\Carbon\Carbon::make($appointment->start_time)->toDateTimeLocalString()}}"
                   type="datetime-local"
                   class="form-control"
                   name="start_time">
        </div>
        <div>
            <input type="submit" name="submit" value="Update appointment">
        </div>
    </form>

@endsection

resources/views/appointments/index.blade.php
@extends('layouts.moran')

@section('title', 'Appointments')

@section('content')

    <h1>Appointments</h1>
    <table>
        <tr>
            @if(auth()->user()->role->name === 'admin')
                <th>
                    <input class="form-check-input"
                           type="checkbox"
                           id="master">
                    <label class="form-check-label" for="master"></label>
                </th>
                <th>@sortablelink('user_id', 'User Name')</th>
                <th>Phone</th>
            @else
                <th>Treatment Cost</th>
            @endif
            <th>@sortablelink('payment_status_id', 'Payment Status')</th>
            <th>@sortablelink('treatment_id', 'Treatment')</th>
            <th>@sortablelink('start_time','Date')</th>
            <th>Time</th>
            <th>@sortablelink('appointment_status_id','Status')</th>
            <th></th>
            @if(auth()->user()->role->name !== 'admin')
                <th></th>
            @endif
        </tr>
        <!-- the table data -->
        @foreach($appointments as $appointment)
            <tr>
                @if(auth()->user()->role->name === 'admin')
                    <td>
                        <input class="form-check-input sub_chk"
                               type="checkbox"
                               name="check-{{$appointment->id}}"
                               data-id="{{$appointment->id}}"
                               id="check-{{$appointment->id}}">
                        <label class="form-check-label" for="check-{{$appointment->id}}"></label>
                    </td>
                    <td>{{$appointment->user->name}}</td>
                    <td>{{$appointment->user->phone}}</td>
                @else
                    <td>{{$appointment->treatment->cost}}</td>
                @endif
                <td>{{$appointment->paymentStatus->name}}</td>
                <td>{{$appointment->treatment->name}}</td>
                <td>{{$appointment->date}}</td>
                <td>{{$appointment->time}}</td>
                <td>{{$appointment->appointmentStatus->name}}</td>
                @if(auth()->user()->role->name === 'admin')
                    <td>
                        <a href="{{route('appointments.edit',$appointment->id)}}">Edit</a>
                    </td>
                        <td>
                            <a href="{{route('appointment.delete',$appointment->id)}}">Delete</a>
                        </td>
                @elseif(\Carbon\Carbon::make($appointment->start_time) > \Carbon\Carbon::now()->addDay())
                    <td>
                        <a href="{{route('appointments.edit',$appointment->id)}}">Edit</a>
                    </td>
                    <td>
                        <a href="{{route('appointment.delete',$appointment->id)}}">Delete</a>
                    </td>
                @endif

            </tr>
        @endforeach

    </table>
    @if(auth()->user()->role->name === 'admin')
        <button class="delete_all" data-url="{{ url('appointments-bulk-delete') }}">Delete All
            Selected
        </button>
    @endif
    {{ $appointments->withQueryString()->links() }}
@endsection